name: kindergarden
description: Kindergarden

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.3
  get_it: ^7.2.0
  retrofit: '>=3.0.0 <4.0.0'
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  package_info: ^2.0.2
  flutter_dotenv: ^4.0.0-nullsafety.1
  hive: ^2.2.1
  get: ^4.6.5
  responsive_framework: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.1.8
  retrofit_generator: '>=4.0.0 <5.0.0'
  hive_generator: ^1.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Caveat
      fonts:
        - asset: lib/presentation/app/ui/fonts/Caveat-Bold.ttf
        - asset: lib/presentation/app/ui/fonts/Caveat-Medium.ttf
        - asset: lib/presentation/app/ui/fonts/Caveat-Regular.ttf
        - asset: lib/presentation/app/ui/fonts/Caveat-SemiBold.ttf
        - asset: lib/presentation/app/ui/fonts/Caveat-VariableFont_wght.ttf
  assets:
    - lib/presentation/app/ui/assets/
    - lib/config/env/development/
    - lib/config/env/production/

